<a href="https://colab.research.google.com/github/stemgene/Python-Diary/blob/master/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
from scipy import ndimage

## Numpy Matrix

#### Create 1D vector and 2D matrix

In [4]:
#row vector
row = np.array([1,2,3]).reshape((1,-1))
row

array([[1, 2, 3]])

In [6]:
# column vector
col = np.array([4,5,6]).reshape((-1,1))
col

array([[4],
       [5],
       [6]])

In [7]:
# two rows 
two_rows = np.array([(1,2,3),(4,5,6)])
two_rows

array([[1, 2, 3],
       [4, 5, 6]])

Creating a NumPy matrix in the same shape as a different array. This uses  `NumPy.empty_like()`:

In [8]:
# Creating ndarray from list
c = np.array([[1., 2.,],[1., 2.]])

# Creating new array in the shape of c, filled with 0
d = np.empty_like(c)
d

array([[1., 1.],
       [1., 0.]])

In [0]:
# A 2×2 2d array shape for the arrays in the format (rows, columns)
shape = (2, 2)

# Random values
c = np.empty(shape)
d = np.ones(shape)
e = np.zeros(shape)

### Slice a matrix

In [0]:
a = np.asarray([[1,1,2,3,4], # 1st row
               [2,6,7,8,9], # 2nd row
               [3,6,7,8,9], # 3rd row
               [4,6,7,8,9], # 4th row
               [5,6,7,8,9]  # 5th row
             ])

b = np.asarray([[1,1],
               [1,1]])

# Select row in the format a[start:end], if start or end omitted it means all range.
y = a[:1]  # 1st row
y = a[0:1] # 1st row
y = a[2:5] # select rows from 3rd to 5th row

# Select column in the format a[start:end, column_number]
x = a[:, –1] # -1 means first from the end
x = a[:,1:3] # select cols from 2nd col until 3rd

### Merge a matrix

#### Concatenate

In [9]:
# 1D 
a = np.array([1, 2, 3])
b = np.array([5, 6])
print(np.concatenate([a, b, b]))

[1 2 3 5 6 5 6]


In [0]:
# 2D
a2 = np.array([[1, 2], [3, 4]])
# axis=0 – concatenate along rows
print np.concatenate((a2, b), axis=0)
# >>   [[1 2]
#       [3 4]
#       [5 6]]

# axis=1 – concatenate along columns, but first b needs to be transposed:
b.T
#>> [[5]
#    [6]]
np.concatenate((a2, b.T), axis=1)
#>> [[1 2 5]
#    [3 4 6]]

#### Append – Append function allows you to add values to the end of a NumPy matrix

In [0]:
# 1d arrays
print np.append(a, a2)
# >> [1 2 3 1 2 3 4]

print np.append(a, a)
# >> [1 2 3 1 2 3]

# 2d arrays. For 2D arrays, both the arrays need to match the shape of the rows.

print np.append(a2, b, axis=0)
# >> [[1 2]
#     [3 4]
#     [5 6]]

print np.append(a2, b.T, axis=1)
# >> [[1 2 5]
#     [3 4 6]]

#### Hstack (stack horizontally) and vstack (stack vertically)

In [0]:
# 1d arrays:

print np.hstack([a, b])
# >> [1 2 3 5 6]

print np.vstack([a, a])
# >> [[1 2 3]
#     [1 2 3]]

3 2d arrays:

print np.hstack([a2,a2]) # arrays must match shape
# >> [[1 2 1 2]
#     [3 4 3 4]]

print np.vstack([a2, b])
# >> [[1 2]
#     [3 4]
#     [5 6]]

#### linespace

In [10]:
a=np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

### Matrix operate

add() − add elements of two matrices.

subtract() − subtract elements of two matrices.

divide() − divide elements of two matrices.

multiply() − multiply elements of two matrices.

dot() − It performs matrix multiplication, does not element wise multiplication.

sqrt() − square root of each element of matrix.

sum(x,axis) − add to all the elements in matrix. Second argument is optional, it is used when we want to compute the column sum if axis is 0 and row sum if axis is 1.

“T” − It performs transpose of the specified matrix.

## Convolution

In [11]:
kernel = np.array([[1/9,1/9,1/9], [1/9,1/9,1/9], [1/9,1/9,1/9]])
image = np.array([[0.0,0.0,0.,0.,0.,0.,0.,0.,0.,0.], 
                  [0.0,0.0,0.,0.,0.,0.,0.,0.,0.,0.], 
                  [0.,0.,0.,90.,90.,90.,90.,90.,0.,0.],
                  [0.,0.,0.,90.,90.,90.,90.,90.,0.,0.],
                  [0.,0.,0.,90.,90.,90.,90.,90.,0.,0.],
                  [0.,0.,0.,90.,90.,90.,90.,90.,0.,0.], 
                  [0.,0.,0.,90.,90.,90.,90.,90.,0.,0.], 
                  [0.0,0.0,0.,0.,0.,0.,0.,0.,0.,0.],
                  [0.0,0.0,0.,0.,0.,0.,0.,0.,0.,0.],
                  [0.0,0.0,0.,0.,0.,0.,0.,0.,0.,0.]],dtype=np.float32)

ndimage.convolve(image, kernel, mode='constant', cval=0.0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 10., 20., 30., 30., 30., 20., 10.,  0.],
       [ 0.,  0., 20., 40., 60., 60., 60., 40., 20.,  0.],
       [ 0.,  0., 30., 60., 90., 90., 90., 60., 30.,  0.],
       [ 0.,  0., 30., 60., 90., 90., 90., 60., 30.,  0.],
       [ 0.,  0., 30., 60., 90., 90., 90., 60., 30.,  0.],
       [ 0.,  0., 20., 40., 60., 60., 60., 40., 20.,  0.],
       [ 0.,  0., 10., 20., 30., 30., 30., 20., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)