<a href="https://colab.research.google.com/github/stemgene/Python-Diary/blob/master/Pandas_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Create DadaFrame

In [0]:
df = pd.DataFrame(data, columns=["col1", "col2","col3"]])

In [0]:
true_list = df.loc[:,'price'][window:].to_list()
pred_list = pred_denorm.tolist()
evaluate_df = pd.DataFrame({"true": true_list, "pred":pred_list})

In [0]:
dd = np.linspace(0,319, 320)
d1 = dd[0:79]
d2 = dd[80:159]
d3 = dd[160:239]
d4 = dd[240: 319]
dd = pd.DataFrame([d1, d2, d3, d4]).transpose()
"""
	 0	   1	    2	    3
0	0.0	80.0	160.0	240.0
1	1.0	81.0	161.0	241.0
2	2.0	82.0	162.0	242.0
3	3.0	83.0	163.0	243.0
4	4.0	84.0	164.0	244.0

### Index

#### Get values of index

In [0]:
df.index[::100]
""" Output . # output is Series
DatetimeIndex(['2010-01-04', '2010-05-27', '2010-10-19', '2011-03-14',
               '2011-08-04', '2011-12-27', '2012-05-21', '2012-10-11',
               '2013-03-11', '2013-08-01', '2013-12-23', '2014-05-19',
               '2014-10-09', '2015-03-05', '2015-07-28', '2015-12-17',
               '2016-05-12', '2016-10-04'],
              dtype='datetime64[ns]', name='date', freq=None)"""
df.index.values[::200] . # output is numpy.array
"""
array(['2010-01-04T00:00:00.000000000', '2010-10-19T00:00:00.000000000',
       '2011-08-04T00:00:00.000000000', '2012-05-21T00:00:00.000000000',
       '2013-03-11T00:00:00.000000000', '2013-12-23T00:00:00.000000000',
       '2014-10-09T00:00:00.000000000', '2015-07-28T00:00:00.000000000',
       '2016-05-12T00:00:00.000000000'], dtype='datetime64[ns]')

### Column

In [0]:
list(pd.column)

### Overview the dataframe

In [0]:
import pandas as pd
import pandas_profiling
df = pd.read_csv('noshowdata.csv')
df.profile_report()

# 2. Edit DadaFrame

#### Delete certain row

In [0]:
cluster_df.drop(cluster_df.index[cluster_df['Neighbourhood'] == 'PARQUE INDUSTRIAL'], inplace = True)

In [0]:
drop=['ILHAS OCEÂNICAS DE TRINDADE', 'PARQUE INDUSTRIAL']
df = df[~df['Neighbourhood'].isin(drop)]

### Create a columm from other column

In [0]:
dataset['ma7'] = dataset['price'].rolling(window=7).mean()

### Insert columns

In [0]:
"""
  data 
0  0
1  1
2  2
3  3
4  4
5  5
6  6
"""
# Introducing weeks as dictionary 
weeks = {0:'Sunday', 1:'Monday', 2:'Tuesday', 3:'Wednesday', 4:'Thursday', 5:'Friday', 6:'Saturday'} 
# Mapping the dictionary keys to the data frame. 
data_frame['new_data_1'] = data_frame['data'].map(weeks) 

""" Outputs
data  new_data_1
0  0  Sunday
1  1  Monday
2  2  Tuesday
3  3  Wednesday
4  4  Thursday
5  5  Friday
6  6  Saturday

In [0]:
df.insert(6, "Date Difference", date_difference)

### Drop column

In [0]:
df = df.drop(['Open', 'High', 'Low'], axis=1)

### Reshape

#### reshape(-1, 1)

https://stackoverflow.com/questions/18691084/what-does-1-mean-in-numpy-reshape

In [0]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])
z.shape
(3, 4)
# -1 means unknown
# reshape(-1)
z.reshape(-1) # 1-D
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# reshape(-1, 1)
z.reshape(-1) 
array([[ 1],
   [ 2],
   [ 3],
   [ 4],
   [ 5],
   [ 6],
   [ 7],
   [ 8],
   [ 9],
   [10],
   [11],
   [12]])

#reshape(1, -1)
z.reshape(1,-1)
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

# reshape(2, -1)
z.reshape(2, -1)
array([[ 1,  2,  3,  4,  5,  6],
   [ 7,  8,  9, 10, 11, 12]])


### Join, merge, and Concatenate

https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

#### Concat

If the index of two tables is same, can easily 'concat' two tables on index

In [0]:
df = pd.concat([df, df_n], axis=1, sort=False)
""" Output
                 price	Volume	NASDAQ price	Russell2000 price	DJI price
Date					
2019-10-25	3022.550049	3370370000	8243.120117	1558.709961	26958.060547
2019-10-28	3039.419922	3521230000	8325.990234	1571.930054	27090.720703
2019-10-29	3036.889893	3589930000	8276.849609	1577.069946	27071.460938
2019-10-30	3046.770020	3776030000	8303.980469	1572.849976	27186.689453
2019-10-31	3037.560059	4139280000	8292.360352	1562.449951	27046.230469

#### Merge

In [0]:
df_merged = df1.merge(df2, how='outer', left_index=True, right_index=True)
""" Outputs
                V1    V2
A 2012-01-01  12.0  15.0
  2012-02-01  14.0   NaN
  2012-03-01   NaN  21.0
B 2012-01-01  15.0  24.0
  2012-02-01   8.0   9.0
C 2012-01-01  17.0   NaN
  2012-02-01   9.0   NaN
D 2012-01-01   NaN   7.0
  2012-02-01   NaN  16.0

#### Join

In [0]:
result = df.join(df_S, how='left')
result.isnull().sum()
""" Outputs, check there are 67 None value in the right column
price          0
SZCZ price    67

# 3. Select from DataFrame



### Select row according to specific value

In [0]:
df[df.Neighbourhood == 'ILHAS OCEÂNICAS DE TRINDADE']

### Iterate rows and columns
https://thispointer.com/pandas-loop-or-iterate-over-all-or-certain-columns-of-a-dataframe/

In [0]:
    Name  Age      City
a   jack   34    Sydney
b   Riti   31     Delhi
c   Aadi   16  New York
d  Mohit   32     Delhi

# Iterate over two given columns only from the dataframe
for column in df[['Name', 'City']]:
   # Select column contents by column name using [] operator
   columnSeriesObj = df[column]
   print('Colunm Name : ', column)
   print('Column Contents : ', columnSeriesObj.values)

"""Outputs:
Colunm Name :  Name
Column Contents :  ['jack' 'Riti' 'Aadi' 'Mohit']
Colunm Name :  City
Column Contents :  ['Sydney' 'Delhi' 'New York' 'Delhi']
"""

Find values with conditions

In [0]:
  New_Visit	Noshow_rate
35  	0	        1.0
36   	1	        0.0
37	  1	        0.0
38	  0	        1.0
39	  1	        0.0
40    0         0.0

status = []
for index, row in noshowdf.iterrows(): 
"""
index = 0, 
row = 
New_Visit 1 
Noshow_rate 0
If want specific value or row, can use either 
row["New_Visit"] or
row[0]
"""
  if row[0] == 1: 
    status.append('New Patient')
  else:
    if row[1] == 0.0:
      status.append('Well-behaved Patient')
    else: # noshow_rate > 0
      status.append("have no show history patient")

"""Outputs:
['have no show history patient',
 'New Patient',
 'New Patient',
 'have no show history patient',
 'New Patient',
 'Well-behaved Patient']
 """

In [0]:
	          symbol	open    	close	    low	         high	     volume
date						
2016-12-30	ZBH	103.309998	103.199997	102.849998	103.930000	973800.0
2016-12-30	ZION	43.070000	43.040001	42.689999	43.310001	1938100.0
2016-12-30	ZTS	53.639999	53.529999	53.270000	53.740002	1701200.0
2016-12-30	AIV	44.730000	45.450001	44.410000	45.590000	1380900.0
2016-12-30	FTV	54.200001	53.630001	53.389999	54.480000	705100.0

df[df.symbol == 'EQIX'].open.values

In [0]:
# It can choose values from a column by certain steps
stocks['open'].loc[::253] #300 is a step len

""" Outputs:
date
2010-01-04     626.951088
2011-01-04     605.621034
2012-01-05     662.131164
2013-01-09     732.271256
2014-01-10    1139.081977
2015-01-13     498.842256
2016-01-14     705.380005
Name: open, dtype: float64

# 4. Cell's Value operation

### Groupby

In [0]:
  New_Visit	Noshow_rate	Status
37	1	          0.0	    New Patient
38	0	          1.0	    have no show history patient
39	1	          0.0	    New Patient

noshowdf.groupby("Status").count()

"""Outputs:
Status	                        New_Visit	Noshow_rate
New Patient	                       61858	61858
Well-behaved Patient	             28291	28291
have no show history patient	     14191	14191
"""

In [0]:
df.groupby('PatientId')['label'].cumsum()

### Change column's value

In [0]:
price_level_cols = ['price', 'ma7', 'ma21','26ema', '12ema', 'upper_band','lower_band','ema','momentum','FFT 3', 'FFT 6', 'FFT 9','ARIMA']
df_normed = df.copy()
df_normed[price_level_cols] = price_normed

### Fill null values

https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html

Check Null value

https://chartio.com/resources/tutorials/how-to-check-if-any-value-is-nan-in-a-pandas-dataframe/

In [0]:
df.isnull().sum()
""" Outputs, check there are 67 None value in the right column
price          0
SZCZ price    67

In [0]:
In [42]: df2
Out[42]: 
        one       two     three four   five  timestamp
a       NaN -0.282863 -1.509059  bar   True        NaT
c       NaN  1.212112 -0.173215  bar  False        NaT
e  0.119209 -1.044236 -0.861849  bar   True 2012-01-01
f -2.104569 -0.494929  1.071804  bar  False 2012-01-01
h       NaN -0.706771 -1.039575  bar   True        NaT

In [43]: df2.fillna(0)
Out[43]: 
        one       two     three four   five            timestamp
a  0.000000 -0.282863 -1.509059  bar   True                    0
c  0.000000  1.212112 -0.173215  bar  False                    0
e  0.119209 -1.044236 -0.861849  bar   True  2012-01-01 00:00:00
f -2.104569 -0.494929  1.071804  bar  False  2012-01-01 00:00:00
h  0.000000 -0.706771 -1.039575  bar   True                    0

In [44]: df2['one'].fillna('missing')
Out[44]: 
a     missing
c     missing
e    0.119209
f    -2.10457
h     missing
Name: one, dtype: object

In [46]: df.fillna(method='pad')
Out[46]: 
        one       two     three
a       NaN -0.282863 -1.509059
c       NaN  1.212112 -0.173215
e  0.119209 -1.044236 -0.861849
f -2.104569 -0.494929  1.071804
h -2.104569 -0.706771 -1.039575

### Map values

In [0]:
df['under18'] =  np.where(df['Age'].astype(int)>18, "no", "yes" )

# Multiclass classifiction




## Labels

### Label encoding

In [0]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df['Label'] = labelencoder.fit_transform(df['Activity'])

#if need inverse label
